### PR TITLE
remove custom logging configuration

### PR DESCRIPTION
**Pull request by 3dik**
See the commit message for the rationale.

If you want to keep the two handlers etc., I suggest that we move that   stuff to a public method ```set_up_dev_logging``` or something like that. Either way, in my opinion, not touching the logging configuration should at least be the default behavior.

### CODE REVIEW

**Comment by tomer8007** [comment]
OK, I get what you're saying. Can you just make `echo_bot.py`'s default logging level set to `INFO`? I like verbose reporting for starters.

**Comment by 3dik** [comment]
Sure, no problem. But are you sure that you mean ```INFO```? Note that, in the other two example scripts, the log level is set to ```DEBUG```.

**Comment by tomer8007** [comment]
Well, in `DEBUG` you see the raw XML that is sent, maybe this is too much. Anyway, these are the current logging levels of the examples (so no need to change them I think).

**Comment by 3dik** [comment]
Got it. I forgot that the removed ```log_level``` argument had a default value ```INFO```.

**Pull request merged**
