### PR TITLE
client.py: create asyncio event loop if needed

### PR DESCRIPTION
**Pull request by gastrodon**
Tries to set event loop, creates one and sets it if one does not exist. Useful for fixing some bugs.

### CODE REVIEW

**Comment by tomer8007** [comment]
What bugs does the current statement create? the [documentation](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) for `get_event_loop` says that if there is no current event loop, a new one will be created.

**Comment by basswaver** [comment]
Hmm, that didn't seem to be the case for me. When importing the library with flask and running `flask run` and trying to make a call to `http://localhost:5000/login` containing the following code

```python
@app.route("/login", methods = ["POST"])
def login():
    payload = json.loads(request.data)
    app.callback = Callback(app)
    app.client = app.callback.client = Client(
        callback = app.callback,
        kik_username = payload["username"],
        kik_password = payload["password"]
    )
    return json.dumps({"username": app.client.username})
```

and where the Client and Callback classes look like 

```python
```

```
 * Serving Flask app "src/py/server.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-04-22 14:22:04,466] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zero/Documents/Programming/kiklient/src/py/server.py", line 33, in login
    kik_password = payload["password"]
  File "/home/zero/Documents/Programming/kiklient/src/py/kik.py", line 20, in __init__
    KikClient.__init__(self, *args, log_level=logging.ERROR, **kwargs)
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/kik_unofficial/client.py", line 59, in __init__
    self.loop = asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
127.0.0.1 - - [22/Apr/2019 14:22:04] "POST /login HTTP/1.1" 500 -
```

**Comment by gastrodon** [comment]
Excuse the delete and re-comment, I'm used to discords need for ctrl+enter

Hmm, that didn't seem to be the case for me. When importing the library with flask and running flask run and trying to make a call to http://localhost:5000/login containing the following code

```python
@app.route("/login", methods = ["POST"])
def login():
    payload = json.loads(request.data)
    app.callback = Callback(app)
    app.client = app.callback.client = Client(
        callback = app.callback,
        kik_username = payload["username"],
        kik_password = payload["password"]
    )
    return json.dumps({"username": app.client.username})
```

and where the Client and Callback classes look like

```python
class Callback(KikClientCallback):
    def __init__(self, app, *args, **kwargs):
        KikClientCallback.__init__(self, *args, **kwargs)
        self.app = app
        self.client = None

    def on_roster_received(self, response):
        r = requests.post("http://localhost:6969/roster", data=response.raw_element.encode("utf-8"))

    def on_authenticated(self):
        self.client.request_roster()


class Client(KikClient):
    def __init__(self, *args, **kwargs):
        KikClient.__init__(self, *args, log_level=logging.ERROR, **kwargs)
        self.jid = None
        self.meta = None

    def update_meta(self, key, value):
        if not self.meta.get(key, False):
            self.meta[key] = []
        self.meta[key].append(value)

```

is netting me 

```
 * Serving Flask app "src/py/server.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-04-22 14:22:04,466] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zero/Documents/Programming/kiklient/src/py/server.py", line 33, in login
    kik_password = payload["password"]
  File "/home/zero/Documents/Programming/kiklient/src/py/kik.py", line 20, in __init__
    KikClient.__init__(self, *args, log_level=logging.ERROR, **kwargs)
  File "/home/zero/Documents/Programming/kiklient/venv/lib/python3.7/site-packages/kik_unofficial/client.py", line 59, in __init__
    self.loop = asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
127.0.0.1 - - [22/Apr/2019 14:22:04] "POST /login HTTP/1.1" 500 -
```

I might be doing something else wrong with flask/python, though if that's the case I'm not sure what. Adding the check seems to resolve this on my end though

**Comment by tomer8007** [comment]
Hmm, I can see several chnages realted to `get_event loop` in [Pyton 3.7](https://docs.python.org/3/whatsnew/3.7.html) and in [Python 3.6](https://docs.python.org/3/whatsnew/3.6.html). Did you try running this code in python 3.7?

Also maybe [this ](https://stackoverflow.com/a/46750562/1806873)solution works for you?

**Comment by gastrodon** [comment]
I've only been using the lib with 3.7.2. I've not tried the solution mentioned instead of using the try-catch block, though I'll do that if it works something or something else more elegant and update you when I'm able

**Comment by gastrodon** [comment]
Suggestion works as a more elegant solution, so the pr has been updated

**Comment by gastrodon** [comment]
Most recent commit fixes an issue in `peers.py` -> `User._parse_entity` with incorrect padding. The length of a base64 string should be divisible by 4 or it will not parse, so `entity` is passed in as `f"{entity}{'='*(len(entity) % 4)}"`

[Info source from stackoverflow](https://stackoverflow.com/questions/6916805/why-does-a-base64-encoded-string-have-an-sign-at-the-end)

**Comment by tomer8007** [comment]
Nice, we already have a method for [decoding base64 with incorrect padding](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/utilities/parsing_utilities.py#L16). It's probably all around kik. Maybe use that?

**Comment by gastrodon** [comment]
My mistake, I didn't see that one. I can't seem to get it to play nice with appending bytes to the string that is passed into it, and when I try to fix it by casting it into bytes it's throwing errors. I'll probably have to take a look at that more when I can, as I'm probably missing something.

**Comment by tomer8007** [comment]
It doesn't seem to decode URL-safe base64, though, so we might need to add this functionality.

**Comment by gastrodon** [comment]
I can probably implement that after work, might be good instead to have a method for padding strings that want to be returned as strings.

**Comment by gastrodon** [comment]
String padding has been added as `ParsingUtilities.base64_string_padding`, and it looks like it works. It just uses the same logic as the inline fix, albeit with the fixed math.

**Comment by tomer8007** [comment]
Oh, the `% 4` logic is already implemented in the `decode_base64` method, so I was thinking more like to add an optional `url_safe` paramter to it and then use `base64.urlsafe_b64decode` if it's true.

**Comment by gastrodon** [comment]
I saw that, though what wants to be padded is a string, I don't know that it's a good idea to have a method either return a string or return `base64.decodebytes(data)` based on what's passed into it. I also don't necessarily want to change the `_parse_entity` method to work with the current `decode_base64` method

**Comment by tomer8007** [comment]
Alright, I get it. Maybe just a better name for `base64_string_padding` would be `fix_base64_padding`?

**Comment by gastrodon** [comment]
I agree, updated

**Pull request merged**
