### PR TITLE
Require device_id for auto login

### PR DESCRIPTION
**Pull request by PointlessUser**
Require device_id for auto login
Make API_key mandatory for sending gifs
Some Refactoring

### CODE REVIEW

**Comment by tomer8007** [comment]
Why would we want to require the device_id for logins? Will the example on the `README.md` still work?

**Comment by PointlessUser** [comment]
> Why would we want to require the device_id for logins? Will the example on the `README.md` still work?

If you sign in with a different device_id  from the one you did the captcha on, you have to re-do the captcha

**Comment by tomer8007** [comment]
OK, but will the example in the README still work or you'll have to supply a device ID?

**Comment by PointlessUser** [comment]
> OK, but will the example in the README still work or you'll have to supply a device ID?

It will work the same. It'll still require a captcha for each login, but it will work. The Device ID is only if you want to bypass the captcha

**Pull request merged**
