### PR TITLE
Added ability to send images.

### PR DESCRIPTION
**Pull request by wolfieanmol**

### CODE REVIEW

**Comment by tomer8007** [comment]
Great feature.
Just a few minor things:

- In `_send_xmpp_element`, I'm not sure: in which situation we would want to send multiple packets at once?
- You forgot to change the docstring of `OutgoingGroupChatImage`.
- I think a better name for `encode_base64` can be `read_file_as_base64` or so (and also rename `image_file`).

**Comment by wolfieanmol** [comment]
Images go out as multiple packets because image data is too big.

And yeah, will fix them.

**Comment by tomer8007** [comment]
Hmm, is there currently a flow in the code in which a `list` is passed to `_send_xmpp_element`?

**Comment by wolfieanmol** [comment]
In the `serialize` method of `OutgoingChatImage`, I'm dividing the data in packets of length 16384.

` packets =  [data[s:s+16384].encode() for s in range(0,len(data), 16384)]`
 `return list(packets)`

When the data is sent as a single packet. The server takes 3-5 seconds to respond with `<ack>` which clearly showed that it was waiting for another packet.
Also, the received image is in multiple packets (2 packets generally).

**Pull request merged**
