### PR TITLE
Merged OutgoingChatMessage and OutgoingGroupChatMessage into OutgoingMessage

### PR DESCRIPTION
**Pull request by hunterbeach**
Merged OutgoingChatMessage and OutgoingGroupChatMessage in chatting.py to simply OutgoingMessage

### CODE REVIEW

**Comment by tomer8007** [comment]
`send_chat_message` doesn't take a parameter named `message_type`, but it's still in the docstring.
Also I think a better name for `OutgoingMessage` would be `OutgoingChatMessage` (We have to distinguish between XMPP stanza types and our classes' names).

**Comment by tomer8007** [comment]
Can you merge `IncomingChatMeessage` and `IncomingGroupChatMessage` too? It'll be more complete in one commit.

**Comment by hunterbeach** [comment]
Whoops, that's what happens at 3AM, forgot to take that out. I'll do those other changes as well.

**Comment by tomer8007** [comment]
Cool

**Comment by hunterbeach** [comment]
I'm not sure the best way to merge those two because both classes need to exist or else it is going to break all the examples and everybody would have to rewrite their program because ```IncomingChatMessage``` and ```IncomingGroupChatMessage``` wouldn't exist anymore.

**Comment by tomer8007** [comment]
Oh yeah, I didn't think about that actually.
Merging only `OutgoingChatMessage` in the same way can break stuff too.
Also having `OutgoingChatMessage` merged while `IncomingChatMessage` isn't can be quite wired. 
I think eventually we will need to make more changes like this or else we'll get stuck with legacy.

It's either we merge both type of classes or we don't merge. If we do, we'll update the examples too. What do you think?

**Comment by hunterbeach** [comment]
Hmm. I was trying to think of some way to keep the legacy functionality intact while still merging both but I can't think of any without a fairly significant effort. Maybe for now we could put these changes that break the current functionality into a separate dev branch so we can accumulate the changes before breaking the current functionality, then eventually merge it into the new branch.

Or, develop on the new branch and push the current new branch into master since master isn't being worked on and is pretty old now.

Whatever we do, I agree we need to try to clean up some code repetition, which may break functionality currently.

**Comment by tomer8007** [comment]
Actually the main problem will be for uses of `IncomingGroupChatMessage` in `on_group_message_received` (Plus people using `on_chat_message_received` and relaying on not getting group messages there).
And after a second look at `IncomingGroupChatMessage`, it contains some additional fields that the regular `IncomingChatMessage` doesn't have.

So, what if we'll make `IncomingGroupChatMessage` and `OutgoingGroupChatMessage` inherit `IncomingChatMessage` and `OutgoingChatMessage`? the clasess would still exist, and we still have a space for extendability.

**Comment by hunterbeach** [comment]
That sound like it should work, I'm just not sure how to implement that into code exactly because I haven't done much with classes and inheritance.

**Comment by tomer8007** [comment]
[Commited that](https://github.com/tomer8007/kik-bot-api-unofficial/commit/60698ff7f75a41923165e4ee785097fed0354a0a).

**Pull request closed without merging**
