### PR TITLE
Multiple bots

### PR DESCRIPTION
**Pull request by kenshin2202**
Is it possible to login to multiple bots using the same script? For a single username/password combination, it's this - username = sys.argv[1] if len(sys.argv) > 1 else input("Username: ")
password = sys.argv[2] if len(sys.argv) > 2 else input('Password: ')

Can I make more username and password variables in the same script and run them? Something like

username1 = sys.argv[1] if len(sys.argv) > 1 else input("Username: ")
password1 = sys.argv[2] if len(sys.argv) > 2 else input('Password: ')

username2 = sys.argv[1] if len(sys.argv) > 1 else input("Username: ")
password2 = sys.argv[2] if len(sys.argv) > 2 else input('Password: ')

### CODE REVIEW

**Comment by tomer8007** [comment]
I guess you could just use multiple `KikClient` instances and alike.

**Comment by kenshin2202** [comment]
I could but won't I have to provide a new device and android ID for every new bot that I make?

**Comment by tomer8007** [comment]
Maybe, but why not just try? 

Also I don't know how is this related to the pull request, if you want to make a group spamming bot then you can just make it in your own fork.

**Comment by Sitiaro** [comment]
https://github.com/tomer8007/kik-bot-api-unofficial/issues/90 <- Refer to this.

**Comment by tomer8007** [comment]
Yes, #90 is promising actually.

**Comment by kenshin2202** [comment]
I'll look into it then thanks for the help!

**Pull request closed without merging**
