### PR TITLE
Implement proper XML parsing, fix QoS parsing / acks, add disable_auth_cert

### PR DESCRIPTION
**Pull request by bluemods**
This aims to enable the client to auto reconnect properly, handle connection failures, and parse stanzas using pull parsing.

Some notes:
- http package was renamed to content, this is required to fix a conflict when attempting to import the sax packages in parser.py
- the parser handles the initial k element manually, then uses a pull parser to figure out where each stanza ends. Then the result is parsed into BeautifulSoup which avoids refactoring the majority of the api which uses BeautifulSoup to navigate
- is_group_jid was changed to be more correct and return a boolean instead of throwing. A method with a `is_` prefix should be returning a boolean by convention, this is a better way to write it.
- We add a new package to requirements called `defusedxml`, this safely parses the xml without trying to resolve entities, DTDs, etc, which XMPP / Kik does not use.
- lxml package is added to assist with xml serialize / deserialize
- We add a new constructor parameter to the Kik Client `disable_auth_cert`, default false. When true, auth cert is skipped. I include this option because generating auth certs is slow, and is generally not needed for most users of the API.
- It probably needs a test by others than me, as there could be a bug or some unexpected behavior changes.

### CODE REVIEW

**Comment by tomer8007** [comment]
Thank you for this awesome pull request.
1. If everything inside the `http` directory deals with HTTP requests, maybe it will be better to rename it to `http_requests`?
2. At which cases you could enable `disable_auth_cert` and can this be automated?

**Comment by bluemods** [comment]
1) I renamed http to http_requests to resolve that
2) auth certs have one purpose, this is to sign JWTs for clients using the Kik browser and wanting to authenticate their account for web requests (like linking their account to a game and proving ownership, or authenticating against a Kik web-service like the sticker and emoji inventories). This functionality is part of the kik.js library, for which the docs have been taken offline but it still works and I have a copy of them. This library doesn't currently implement the functionality to create JWTs / sign requests, so it won't have a use for most people.

I made an [archive](https://archive.ph/bKkDo) of the kik.js docs. Search for kik.sign to read more about it

**Comment by tomer8007** [comment]
Oh I see. So the auth cert request was added by @kandnub in 9ea8795063a353a212b8b8383f12c97469ddc729. Do you think we can have `disable_auth_cert=True` by default? Or even remove the `self.authenticator.send_stanza()` line?

**Comment by bluemods** [comment]
> Oh I see. So the auth cert request was added by @kandnub in [9ea8795](https://github.com/tomer8007/kik-bot-api-unofficial/commit/9ea8795063a353a212b8b8383f12c97469ddc729). Do you think we can have `disable_auth_cert=True` by default? Or even remove the `self.authenticator.send_stanza()` line?

True by default, sure, but I don't see a reason to remove it entirely.

**Comment by tomer8007** [comment]
> I don't see a reason to remove it entirely.

We won't remove the `AuthStanza` class of course, but why would anyone want to create a bot with `disable_auth_cert=False`? Can you give one example?

**Comment by bluemods** [comment]
JWT signing / requests could be implemented for interacting with websites or unlocking all the emotes in Kik's emote shop, for example. But it is a very niche use case so I did change it to be disabled by default.

**Pull request merged**
