### PR TITLE
Classes and callbacks

### LINKED ISSUE #17: Classes and callbacks
There's a couple of issues with the current codebase. First of all some methods are long and messy. It would be nice to do a major refactor. Let's gather some ideas.

- Use classes for users, groups, messages. Peer (with jid) is extended by User and Group, Group is extended by PublicGroup and PrivateGroup.
- Instead of the user having to figure out the type of the next message, let the user extend a KikClient and implement callback functions for the ones they're going to use. E.g. for a simple bot this would result in something like this:
```python
class MyKikBot(KikClient):
    def on_group_message(self, group_message: GroupMessage):
        group.send(GroupMessage("You sent: {}".format(group_message.message)))
```
- The current API can't send and receive messages simultaneously because they both "claim" the socket. The way around this is to keep track of message ids, do sending and receiving asynchronously, this would go along nicely with previous point.

Maybe I could make a basic version of this. Anyway, we can use this thread for future plans.

### PR DESCRIPTION
**Pull request by Jaapp-**
Fixes #17 

This is what I came up with. Python's asyncio Protocol handles the async networking.

Every outgoing message has a method in api.py which creates a Message.
Incoming messages are parsed by their xmlns handler, and then returned to callback.

Most things of the current code are implemented, content messages aren't. Might want to delete current KikClient eventually to keep the codebase clean.

### CODE REVIEW

**Comment by tomer8007** [comment]
Great, I will go over it as soon as I could (probably in a week)

**Comment by tomer8007** [comment]
Good work, much appreciated. asyncio looks great too

I have a number of questions/enhancements that could be done:
1. What's the common meaning of files under the `unauthorized` folder? I'm not sure I understand why `register.py` and `checkunique.py` are there.
2. We have to distinguish between XMPP stanza types and our classes' names. The [XMPP RFC](https://xmpp.org/rfcs/rfc3920.html) says that:
**A**. The `<message/>` stanza is basically when one entity sends or receives information from/to another entity. So a read receipt we get or send is a `<message>`, a chat message is a `<message>`, and 'is-typing' status is a  `<message>`. 
**B**. The `<iq/>` stanza stands for Info/Query - request and response. Usually the `type` of a request  `<iq/>` stanza is `get` or `set`, and the type of a response `<iq/>` stanza is either `response` or `error`. Examples of these are requests to login, to get roster, to sign up, or to get information about JIDs.

    However I want our code to use more sensable terms in names of classes. I think better names for classes like `LoginMessage` , `RegisterMessage` could be `LoginRequest`, `RegisterRequest` and so on. Also I think we need to distinguish between `Response`s and `Event`s.
So what did you mean by `Message`? As you use it, for me it looks like an XML element that has a kik UUID attached. It will be helpful if you could explain the idea behind the classes.

3. Maybe it'll be better to separate each class to its own file? Make the project more structural? Folders like `errors`, `chat`, `group_adminship`, `handlers`?
4. Are you sure handlers are necessary? They basicaly just call the callbacks. Usually when I program stuff like this I just pass a callback and call the appropriate functions. I mean, you can say that whenever someone makes a subcalass of `KikCallback` and one of its functions fire, it will **handle** the event. As an alternative we could insert `handle_YYY` functions into `KikApi`. I know handleres were meant to abstract the code but I think that because of the xmlns catagories the code becomes less trackable. 

Generally speaking, there are a couple of more renames and refactoring that I would like to do later on sometime.

**Comment by Jaapp-** [comment]
No problem, I expect a bunch of changes yet to be made.

1. The `unauthorized` folder includes all stanzas that don't require an authorized connection, maybe this can be used to throw an exception when e.g. someone tries sending a message before logging in. Checking whether a username exists and logging in or registering don't require such authorized connection.
2. Yeah, I'll admit that's kind of awkard. My first approach was to call every `<message>` stanza (incoming and outgoing) Message and every `<iq>` Iq, but later I figured it would be more sensible to clearly differentiate between outgoing and incoming messages. The code would get pretty complex if using a single class for both incoming and outgoing traffic of some sort. I chose Message for all outgoing traffic and Response for all incoming traffic.

I propose this:
Outgoing
- `<message>` => Message as it is
- `<iq>` => Request

Incoming
- `<message>` => MessageEvent (??)
- `<iq>` => Result or Error


Some kind of mechanism to call get_roster, wait mid-function without stopping program execution and continuing with the result would be convenient. Asyncio should be able to do that, I'm not sure how.

3. It has gotten somewhat messy over time and a restructure would work. The main reason of the clutter is a Python problem. Typehints require imports, and circular dependencies are not allowed in Python. For example KikApi creates a KikConnection, but KikConnection makes calls to the Api. I wanted autocomplete for the KikApi calls in KikConnection, so I used a typehint, this makes for a circular dependency and only works if KikApi and KikConnection are contained in the same file. This is also the reason that Handlers doesn't have its reference to api typehinted. Which is a shame.

4. The main problem here is that responses need to be categorized beyond their xmlns and type. That's the current responsibility of handlers. `hanlde_YYY` would also be fine.

**Comment by tomer8007** [comment]
Alright, I've done a little re-structure of the source in branch `new`. We need to add more logs for making requests, like the old one (''[+] Logging in...") and also make sure joining groups work.

**Pull request merged**
