### PR TITLE
Add failsafe for protobuf parsing

### PR DESCRIPTION
**Pull request by Jaapp-**
This worked when I implemented it but now it's throwing some exceptions, so let's be careful.

### CODE REVIEW

**Comment by tomer8007** [comment]
Do you know why is it throwing the exceptions?

**Comment by Jaapp-** [comment]
An "incorrect padding" error. I'm a bit quick about it because it was messing up other things and I don't have much time currently.

**Comment by tomer8007** [comment]
Hmm. We already have a method for [decoding base64 with incorrect padding](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/utilities/parsing_utilities.py#L16).

**Comment by Jaapp-** [comment]
Fair enough. I'll try it out

**Comment by Jaapp-** [comment]
I found that base64.urlsafe_b64decode from the standard library does the job where our implementation still raises some exceptions.

**Pull request closed without merging**
